hw1 added
Shasha33/JavaHW pull request #1
Opened 2019-01-22 10:07 UTC by Shasha33

2019-01-22 14:39 UTC, yurii-litvinov requested changes

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +public class HashTable {
Самому классу тоже нужен комментарий, и это даже важнее, чем комментарии к методам --- потому что единицей декомпозиции объектно-ориентированной программы является именно класс, и про каждый класс должно быть понятно, что он делает и зачем нужен.

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +    private int size, cnt;
Лучше каждое поле объявлять отдельно. Объявление cnt при беглом просмотре программы легко не заметить.

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +    private int size, cnt;
Вообще, лучше никогда не сокращать идентификаторы. cnt может расшифровываться как count (и тогда count чего?), может как continuation или ещё что-нить. Написать код надо один раз, а разбираться в нём может потребоваться часто, много, разным людям.

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +    public HashTable(int size){
Надо пробел перед каждой фигурной скобкой

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +        cnt = 0;
Вообще, оно и так инициализируется нулём при создании объекта, так что это можно не писать

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +            table[i] = new List();
Надо фигурные скобки вокруг тела цикла, даже если там всего один оператор.

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +        return (table[getIndex(key)].findValueByKey(key) != null);
Так оно упадёт, если в качестве key передать null

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +        return key.hashCode() % size;
hashCode() может возвращать отрицательное значение, % тоже, а код ниже к этому морально не готов. Так что оно **иногда** будет падать --- на длинных строках, некоторых строках национальных алфавитов и т.д.

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +        List curList = table[getIndex(key)];
Тут тоже, не надо сокращать имена. Буквы пока бесплатны, этим надо пользоваться :)

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +        String old_value = curList.findValueByKey(key);
camelCase, пожалуйста

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +            cnt++;
И тут надо фигурные скобки

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +            cnt++;
Хмм, а если мы реально хотим хранить null в таблице?

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +
Вообще, лучше комментарии от кода пустыми строками не отделять

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +            cnt++;
И хотелось бы динамического изменения размера хеш-таблицы, иначе она быстро выродится в линейную трудоёмкость операций.

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +            cnt++;
Мм?

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/List.java
> +        head = tail = null;
Лучше одно присваивание за раз, опять-таки по соображениям читаемости

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/List.java
> +        Node newNode = new Node (new PairStrStr (key, value), null, null);
Пробел между Node и ( не нужен

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/List.java
> +        Node newNode = new Node (new PairStrStr (key, value), null, null);
Кстати, тут тип переменной очевиден из правой части присваивания, так что тут лучше использовать var

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/List.java
> +            head = tail = newNode;
Тут тоже. Вообще, есть хорошее правило "один оператор на одной строке", тут всё-таки два оператора, хотя и записанных вместе.

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/List.java
> +            cur = cur.next;
Тут тоже надо фигурные скобки (и ниже)

2019-01-22 14:39 UTC, yurii-litvinov commented on HashTable/src/test/java/com/hw/hashtable/HashTableTest.java
> +        HashTable ht = new HashTable(10);
Имеет смысл использовать @BeforeEach для инициализации хеш-таблицы, а то копипаст

2019-01-25 21:19 UTC, Shasha33 commented
Извиняюсь за большой комит, но было бы странно убирать изменения и комитить частями

2019-01-27 07:23 UTC, yurii-litvinov requested changes

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +import java.security.InvalidParameterException;
В документации написано, что это исключение "designed for use by the JCA/JCE engine classes", так что бросать его, несмотря на удачное название, может быть плохой идеей. То, что оно определено в java.security, тоже намекает. IllegalArgumentException лучше.

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +    private int size;
Есть подозрение, что size == table.length всегда. Если это правда, то size можно не хранить.

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +        for(int i = 0; i < size; i++) {
Надо пробел между for и скобкой

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +
А вот много лишних пустых строк не надо, обычно рекомендуют не больше одной подряд.

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +        for(int i = 0; i < size / 2; i++) {
Пробела не хватает

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +            String currentKey, currentValue;
Лучше объявлять по одной переменной за раз.

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +            while((currentKey = currentList.getHeadKey()) != null) {
И тут пробела не хватает

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +
Напоминаю

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/HashTable.java
> +        List curList = table[getIndex(key)];
Напоминаю :)

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/List.java
> +        private String key, value;
Тут тоже правильнее объявлять каждое поле отдельно

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/List.java
> +
И тут тоже лишние пустые строки

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/List.java
> +        private Node next, previous;
И тут, переменные должны объявляться отдельно

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/List.java
> +        private void setNext(Node next){
А тут пробела не хватает

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/List.java
> +        else{
А else должен быть на предыдущей строчке, и с пробелом беда

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/test/java/com/hw/hashtable/HashTableTest.java
> +        assertTrue(c1 && c2 && c3 && c4 && c5);
Ой. Лучше это делать отдельными assertEquals, если хотите увидеть в логе внятное сообщение о том, что сломалось.

2019-01-27 07:23 UTC, yurii-litvinov commented on HashTable/src/test/java/com/hw/hashtable/HashTableTest.java
> +        assertNull( hashTable.get("a"));
А тут лишний пробел

2019-01-29 09:55 UTC, yurii-litvinov approved these changes
Ещё пара замачаний осталась, но в целом всё ок, так что зачтена

2019-01-29 09:55 UTC, yurii-litvinov commented on HashTable/src/main/java/com/hw/hashtable/List.java
> +    private Node head, tail;
Поля лучше объявлять каждое отдельно

2019-01-29 09:55 UTC, yurii-litvinov commented on HashTable/src/test/java/com/hw/hashtable/HashTableTest.java
> +        assertEquals(hashTable.size(), 0);
Наоборот, сначала что ожидается, затем что получилось. Выше же правильно

2019-01-31 17:42 UTC, merged