Reflector added
Shasha33/JavaHW pull request #7
Opened 2019-03-10 12:06 UTC by Shasha33

Не хватает теста, который бы сравнивал распечатанный класс с исходным, так как я не понимаю, как он должен собираться без реализации методов.

2019-03-12 08:54 UTC, yurii-litvinov requested changes
- extends java.lang.Object не надо печатать
- В идеале ещё бы import-ы для используемых пакетов (в совсем идеале --- для часто используемых пакетов)

2019-03-12 08:54 UTC, yurii-litvinov commented on Reflector/src/main/java/com/hw/ref/Reflector.java
> +        writer.print(parametersList.stream().collect( Collectors.joining( ", " ) ));
Я бы сказал "лишние пробелы вокруг и внутри `Collectors.joining( ", " )`" :)

2019-03-12 08:54 UTC, yurii-litvinov commented on Reflector/src/main/java/com/hw/ref/Reflector.java
> +            writer.print(parameter.getTypeName() + " " + name);
Есть же getParameters(), из которого можно достать настоящие имена параметров

2019-03-12 08:54 UTC, yurii-litvinov commented on Reflector/src/main/java/com/hw/ref/Reflector.java
> +        return "<" +list.stream().map(TypeVariable::getName).collect( Collectors.joining(", ")) + ">";
Пробела не хватает

2019-03-12 08:54 UTC, yurii-litvinov commented on Reflector/src/main/java/com/hw/ref/Reflector.java
> +     * Due to absense of implementation in methods and contrustors recieved file can not be builded,
contrustors :)

2019-03-12 08:54 UTC, yurii-litvinov commented on Reflector/src/main/java/com/hw/ref/Reflector.java
> +        resault += " throws " + List.of(exceptionList)
resault?

2019-03-12 08:54 UTC, yurii-litvinov commented on Reflector/src/main/java/com/hw/ref/Reflector.java
> +    public static final String fileName = "src/test/java/com/hw/ref/SomeClass.java";
Надо его всё-таки назыввать как класс, который в нём содержится. SomeClass в условии было дано просто как пример

2019-03-12 08:54 UTC, yurii-litvinov commented on Reflector/src/test/java/com/hw/ref/ReflectorTest.java
> +        compiler.run(null, null, null,  "src/test/java/com/hw/ref/SomeClass.java");
Имя файла с полным путём есть копипаст, а копипаст есть ересь

2019-03-12 12:50 UTC, Shasha33 commented on Reflector/src/main/java/com/hw/ref/Reflector.java
> +            writer.print(parameter.getTypeName() + " " + name);
из getParameters() не получается достать типы так, чтобы сохранить генериковость

2019-03-17 11:51 UTC, yurii-litvinov requested changes

2019-03-17 11:51 UTC, yurii-litvinov commented on Reflector/src/main/java/com/hw/ref/Reflector.java
> +
Лишняя пустая строчка :)

2019-03-17 11:51 UTC, yurii-litvinov commented on Reflector/src/test/answers/ClassWithInterfacePrinted
> +    private abstract static interface interface InnerInterface  extends MyInterface, CoolInterface {
interface interface? Кстати, интерфейсы и так abstract, это не надо печатать

2019-03-18 05:15 UTC, yurii-litvinov approved these changes
Ага, зачтена

2019-04-14 15:11 UTC, merged